const D='data/';
const files=['kpis','trend_morosidad','regions','communes','institutions','banks','annual_finance','ies_types','quality','sources'];
const fmtN=new Intl.NumberFormat('es-CL');
const fmtPct=v=>v==null?'s/d':new Intl.NumberFormat('es-CL',{style:'percent',maximumFractionDigits:1}).format(v);
const fmtMoney=v=>'$'+new Intl.NumberFormat('es-CL',{notation:'compact',maximumFractionDigits:2}).format(v);
const fmtCLP=v=>v==null?'s/d':'$'+fmtN.format(v);
const colors={ink:'#14241f',green:'#0f5b45',green2:'#18765a',lime:'#d8f06b',orange:'#e6683c',gray:'#aab6b0',paper:'#f7f3eb'};
const baseLayout={font:{family:'Inter, system-ui, sans-serif',color:colors.ink},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',margin:{l:55,r:20,t:25,b:50},hoverlabel:{bgcolor:colors.ink,font:{color:'#fff'}},legend:{orientation:'h',y:1.12},xaxis:{gridcolor:'#e6ebe7',zeroline:false},yaxis:{gridcolor:'#e6ebe7',zeroline:false}};
const config={displayModeBar:false,responsive:true,locale:'es'};
let data={},geo;
// Las claves normalizadas se reservan exclusivamente para joins. Toda etiqueta
// visible sale de las columnas legibles publicadas en los extractos.
const displayComuna=d=>d.comuna||'Comuna sin nombre';
const displayRegion=d=>d.region||'Región sin nombre';
const displayInstitucion=d=>d.institucion||'Institución sin nombre';

async function load(){
  const loaded=await Promise.all(files.map(async f=>[f,await fetch(`${D}${f}.json`).then(r=>{if(!r.ok)throw Error(f);return r.json()})]));
  data=Object.fromEntries(loaded); geo=await fetch(`${D}communes.geojson`).then(r=>r.json());
  renderAll();
}
function renderAll(){renderKpis();fillFilters();renderTrend();renderTerritory();renderInstitutions();renderFinance();renderMethod();bind();}
function renderKpis(){const k=data.kpis;$('kpi-debt').textContent=fmtMoney(k.saldo_total_clp);$('kpi-arrears').textContent=fmtN.format(k.morosos_n);$('kpi-rate').textContent=fmtPct(k.tasa_morosidad);$('hero-rate').textContent=fmtPct(k.tasa_morosidad);$('kpi-guarantees').textContent=fmtN.format(k.garantias_ejecutadas_n)}
function fillFilters(){[...new Set(data.communes.map(displayRegion))].sort().forEach(v=>$('region-filter').add(new Option(v,v)));[...new Set(data.institutions.map(d=>d.tipo_ies).filter(Boolean))].sort().forEach(v=>$('ies-filter').add(new Option(v,v)))}
function renderTrend(){const order=['Desertor/a','Egresado/a','Total'];const palette=[colors.orange,colors.green2,colors.ink];const traces=order.map((g,i)=>{const a=data.trend_morosidad.filter(d=>d.tipo_deudor===g);return{x:a.map(d=>String(d.anio)),y:a.map(d=>d.tasa_morosidad),name:g,type:'bar',marker:{color:palette[i]},hovertemplate:`${g}<br>%{x}: %{y:.1%}<extra></extra>`}});Plotly.newPlot('trend-chart',traces,{...baseLayout,barmode:'group',yaxis:{...baseLayout.yaxis,tickformat:'.0%',range:[0,1]},xaxis:{...baseLayout.xaxis,type:'category'}},config);renderTrendInterpretation()}
const metricMeta={tasa_morosidad_total:['Tasa de morosidad total','pct'],total_deudores_n:['Total deudores/as','n'],total_al_dia_n:['Personas al día','n'],total_morosos_n:['Personas morosas','n'],tasa_morosidad_desertores:['Morosidad de desertores','pct'],tasa_morosidad_egresados:['Morosidad de egresados','pct'],ingreso_autonomo_promedio_hogar_clp:['Ingreso promedio del hogar','clp'],ingreso_autonomo_mediano_hogar_clp:['Ingreso mediano del hogar','clp'],tasa_pobreza_ingresos:['Pobreza por ingresos','pct']};
function renderTerritory(){const region=$('region-filter').value,metric=$('metric-filter').value,[label,kind]=metricMeta[metric];const rows=data.communes.filter(d=>region==='ALL'||displayRegion(d)===region);const keys=new Set(rows.map(d=>d.comuna_clave));const features=geo.features.filter(f=>keys.has(f.properties.comuna_clave));const subgeo={type:'FeatureCollection',features};const z=features.map(f=>f.properties[metric]);const zTemplate=kind==='pct'?'%{z:.1%}':kind==='clp'?'$%{z:,.0f}':'%{z:,.0f}';Plotly.react('map-chart',[{type:'choropleth',geojson:subgeo,featureidkey:'properties.comuna_clave',locations:features.map(f=>f.properties.comuna_clave),z,colorscale:[[0,'#eef3ef'],[.35,'#a5d3b8'],[.7,'#2b8063'],[1,'#103d31']],marker:{line:{color:'#fff',width:.35}},colorbar:{title:kind==='pct'?'%':kind==='clp'?'$':'N',thickness:12},customdata:features.map(f=>[f.properties.comuna,f.properties.region,f.properties.total_deudores_n,f.properties.total_al_dia_n,f.properties.total_morosos_n,fmtPct(f.properties.tasa_morosidad_total),fmtCLP(f.properties.ingreso_autonomo_promedio_hogar_clp),fmtCLP(f.properties.ingreso_autonomo_mediano_hogar_clp),fmtPct(f.properties.tasa_pobreza_ingresos)]),hovertemplate:'<b>%{customdata[0]}</b><br>%{customdata[1]}<br>'+label+': '+zTemplate+'<br><br>Total deudores/as: %{customdata[2]:,.0f}<br>Al día: %{customdata[3]:,.0f}<br>Morosos/as: %{customdata[4]:,.0f}<br>Tasa de morosidad: %{customdata[5]}<br>Ingreso promedio: %{customdata[6]}<br>Ingreso mediano: %{customdata[7]}<br>Pobreza: %{customdata[8]}<extra></extra>'}],{...baseLayout,margin:{l:0,r:0,t:0,b:0},geo:{fitbounds:'locations',visible:false,bgcolor:'rgba(0,0,0,0)'}},config);
  const scatter=rows.filter(d=>d.tasa_pobreza_ingresos!=null&&d.tasa_morosidad_total!=null);Plotly.react('poverty-chart',[{type:'scatter',mode:'markers',x:scatter.map(d=>d.tasa_pobreza_ingresos),y:scatter.map(d=>d.tasa_morosidad_total),text:scatter.map(displayComuna),customdata:scatter.map(d=>[displayRegion(d),d.total_morosos_n]),marker:{size:scatter.map(d=>Math.max(6,Math.sqrt(d.total_deudores_n)*.35)),sizemode:'diameter',color:scatter.map(d=>d.total_morosos_n),colorscale:[[0,'#b8d6c8'],[1,colors.orange]],opacity:.75,line:{color:'#fff',width:.5}},hovertemplate:'<b>%{text}</b><br>%{customdata[0]}<br>Pobreza: %{x:.1%}<br>Morosidad: %{y:.1%}<br>Morosos/as: %{customdata[1]:,.0f}<extra></extra>'}],{...baseLayout,margin:{l:55,r:15,t:15,b:55},xaxis:{...baseLayout.xaxis,tickformat:'.0%',title:'Pobreza comunal'},yaxis:{...baseLayout.yaxis,tickformat:'.0%',title:'Morosidad CAE'}},config);renderCommuneTable(rows);renderTerritoryInterpretations(rows,region,metric,scatter)}
function renderCommuneTable(rows){const ranked=[...rows].sort((a,b)=>b.total_morosos_n-a.total_morosos_n);$('commune-count').textContent=`${rows.length} comunas`;const tbody=$('commune-table');tbody.innerHTML=ranked.map(d=>`<tr><td><b>${esc(displayComuna(d))}</b></td><td>${esc(displayRegion(d))}</td><td class="num">${fmtN.format(d.total_deudores_n)}</td><td class="num">${fmtN.format(d.total_al_dia_n)}</td><td class="num">${fmtN.format(d.total_morosos_n)}</td><td class="num">${fmtPct(d.tasa_morosidad_total)}</td><td class="num">${fmtCLP(d.ingreso_autonomo_promedio_hogar_clp)}</td><td class="num">${fmtCLP(d.ingreso_autonomo_mediano_hogar_clp)}</td><td class="num">${fmtPct(d.tasa_pobreza_ingresos)}</td></tr>`).join('')}
function renderInstitutions(){const filter=$('ies-filter').value;const rows=data.institutions.filter(d=>(filter==='ALL'||d.tipo_ies===filter)&&!/^Total/i.test(displayInstitucion(d)));const top=[...rows].sort((a,b)=>b.morosos_total_n-a.morosos_total_n).slice(0,15).reverse();Plotly.react('institution-bar',[{type:'bar',orientation:'h',x:top.map(d=>d.morosos_total_n),y:top.map(d=>short(displayInstitucion(d),34)),marker:{color:top.map(d=>d.tasa_morosidad_total),colorscale:[[0,'#8fc2ab'],[1,colors.orange]]},customdata:top.map(d=>[displayInstitucion(d),d.tasa_morosidad_total,d.tipo_ies]),hovertemplate:'<b>%{customdata[0]}</b><br>%{customdata[2]}<br>Morosos/as: %{x:,.0f}<br>Tasa: %{customdata[1]:.1%}<extra></extra>'}],{...baseLayout,margin:{l:220,r:15,t:10,b:45},xaxis:{...baseLayout.xaxis,title:'Personas morosas'}},config);const cross=rows.filter(d=>d.recursos_cae_mm_clp_dic2023!=null&&d.tasa_morosidad_total!=null);Plotly.react('institution-scatter',[{type:'scatter',mode:'markers',x:cross.map(d=>d.recursos_cae_mm_clp_dic2023),y:cross.map(d=>d.tasa_morosidad_total),text:cross.map(displayInstitucion),customdata:cross.map(d=>[d.tipo_ies,d.morosos_total_n]),marker:{size:cross.map(d=>Math.max(7,Math.sqrt(d.morosos_total_n)*.42)),color:colors.green2,opacity:.66,line:{color:'#fff',width:1}},hovertemplate:'<b>%{text}</b><br>%{customdata[0]}<br>Recursos: $%{x:,.0f} MM<br>Morosidad: %{y:.1%}<br>Morosos/as: %{customdata[1]:,.0f}<extra></extra>'}],{...baseLayout,xaxis:{...baseLayout.xaxis,title:'Recursos CAE (MM$ dic. 2023)'},yaxis:{...baseLayout.yaxis,title:'Tasa de morosidad',tickformat:'.0%'}},config);renderInstitutionInterpretations(rows,cross,filter)}
function renderFinance(){const a=data.annual_finance;Plotly.newPlot('finance-chart',[{type:'bar',x:a.map(d=>d.periodo),y:a.map(d=>d.monto_creditos_cursados_mm_clp_dic2023),name:'Créditos cursados',marker:{color:colors.green2},hovertemplate:'%{x}<br>$%{y:,.0f} MM<extra></extra>'},{type:'bar',x:a.map(d=>d.periodo),y:a.map(d=>d.monto_recomprado_mm_clp_dic2023),name:'Recomprados',marker:{color:colors.orange},hovertemplate:'%{x}<br>$%{y:,.0f} MM<extra></extra>'}],{...baseLayout,barmode:'group',xaxis:{...baseLayout.xaxis,type:'category'},yaxis:{...baseLayout.yaxis,title:'MM$ dic. 2023'}},config);const b=[...data.banks].sort((x,y)=>y.monto_recomprado_mm_clp_dic2023-x.monto_recomprado_mm_clp_dic2023).reverse();Plotly.newPlot('bank-chart',[{type:'bar',orientation:'h',y:b.map(d=>short(d.banco,24)),x:b.map(d=>d.monto_recomprado_mm_clp_dic2023),name:'Monto recomprado',marker:{color:colors.green},hovertemplate:'%{y}<br>$%{x:,.0f} MM<extra></extra>'},{type:'bar',orientation:'h',y:b.map(d=>short(d.banco,24)),x:b.map(d=>d.recarga_mm_clp_dic2023),name:'Recarga',marker:{color:colors.orange},hovertemplate:'%{y}<br>$%{x:,.0f} MM<extra></extra>'}],{...baseLayout,barmode:'stack',margin:{l:150,r:15,t:25,b:45},xaxis:{...baseLayout.xaxis,title:'MM$ dic. 2023'}},config);renderFinanceInterpretations(a,b)}
function sum(rows,field){return rows.reduce((acc,d)=>acc+(Number(d[field])||0),0)}
function correlation(rows,xField,yField){const pairs=rows.map(d=>[Number(d[xField]),Number(d[yField])]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y));if(pairs.length<3)return null;const mx=pairs.reduce((a,p)=>a+p[0],0)/pairs.length,my=pairs.reduce((a,p)=>a+p[1],0)/pairs.length;const num=pairs.reduce((a,p)=>a+(p[0]-mx)*(p[1]-my),0),dx=Math.sqrt(pairs.reduce((a,p)=>a+(p[0]-mx)**2,0)),dy=Math.sqrt(pairs.reduce((a,p)=>a+(p[1]-my)**2,0));return dx&&dy?num/(dx*dy):null}
function interpretation(id,html){$(id).innerHTML=html}
function renderTrendInterpretation(){const latest=Math.max(...data.trend_morosidad.map(d=>Number(d.anio)));const get=t=>data.trend_morosidad.find(d=>Number(d.anio)===latest&&d.tipo_deudor===t)?.tasa_morosidad;interpretation('trend-interpretation',`En ${latest}, la morosidad alcanzó <b>${fmtPct(get('Total'))}</b>: ${fmtPct(get('Desertor/a'))} entre quienes desertaron y ${fmtPct(get('Egresado/a'))} entre quienes egresaron. La persistencia en ambos grupos muestra que el problema excede una trayectoria individual y respalda una respuesta universal, no ayudas restringidas a casos excepcionales.`)}
function renderTerritoryInterpretations(rows,region,metric,scatter){const scope=region==='ALL'?'las comunas con información territorial':`la región de ${region}`;const debtors=sum(rows,'total_deudores_n'),arrears=sum(rows,'total_morosos_n'),rate=debtors?arrears/debtors:null;const incomeMetric=metric.startsWith('ingreso_'),coverage=rows.filter(d=>d[metric]!=null).length;const metricText=incomeMetric?`El indicador de ingreso seleccionado está publicado para <b>${coverage} de ${rows.length} comunas</b> del filtro; la ausencia de dato no equivale a ingreso cero.`:`En ${scope} se observan <b>${fmtN.format(arrears)} personas morosas</b> entre ${fmtN.format(debtors)} deudores/as (${fmtPct(rate)}).`;interpretation('map-interpretation',`${metricText} El patrón territorial hace visible que la deuda se distribuye socialmente por todo el país; las diferencias locales modifican la intensidad, pero no eliminan el carácter nacional del conflicto.`);const r=correlation(scatter,'tasa_pobreza_ingresos','tasa_morosidad_total');const relation=r==null?'no puede resumirse con estabilidad':`presenta una correlación descriptiva de <b>r=${r.toFixed(2)}</b>`;interpretation('poverty-interpretation',`Para ${scope}, el cruce entre pobreza y morosidad ${relation}. Esto no prueba causalidad ni identifica la condición de cada persona: muestra contextos territoriales y desaconseja convertir la morosidad en un juicio moral individual.`)}
function renderInstitutionInterpretations(rows,cross,filter){const top=[...rows].filter(d=>Number.isFinite(Number(d.morosos_total_n))).sort((a,b)=>b.morosos_total_n-a.morosos_total_n)[0];const scope=filter==='ALL'?'todas las instituciones':filter;if(top){interpretation('institution-bar-interpretation',`En ${scope}, <b>${esc(displayInstitucion(top))}</b> registra la mayor cantidad publicada: ${fmtN.format(top.morosos_total_n)} personas morosas (${fmtPct(top.tasa_morosidad_total)}). La concentración por plantel muestra que las consecuencias del CAE fueron producidas dentro de un sistema institucional, no por decisiones aisladas de cada deudor/a.`)}else interpretation('institution-bar-interpretation','No hay instituciones con datos suficientes para el filtro seleccionado.');const r=correlation(cross,'recursos_cae_mm_clp_dic2023','tasa_morosidad_total');interpretation('institution-scatter-interpretation',`El cruce cubre <b>${cross.length} instituciones</b>${r==null?'':` y muestra una correlación descriptiva de <b>r=${r.toFixed(2)}</b>`} entre recursos CAE recibidos y tasa de morosidad. No establece causalidad, pero permite confrontar la expansión financiera institucional con sus resultados sociales.`)}
function renderFinanceInterpretations(annual,banks){const issued=sum(annual,'monto_creditos_cursados_mm_clp_dic2023'),repurchased=sum(annual,'monto_recomprado_mm_clp_dic2023'),surcharge=sum(annual,'recarga_mm_clp_dic2023');interpretation('finance-interpretation',`Entre 2006 y 2023 se cursaron <b>${fmtCLP(issued*1e6)}</b> y se recompraron ${fmtCLP(repurchased*1e6)}, equivalentes al ${fmtPct(repurchased/issued)} del monto cursado. El Estado no fue un espectador: absorbió una parte sustantiva del mecanismo que sostuvo el mercado del CAE.`);const top=[...banks].sort((a,b)=>b.monto_recomprado_mm_clp_dic2023-a.monto_recomprado_mm_clp_dic2023).pop();const totalBankSurcharge=sum(banks,'recarga_mm_clp_dic2023');interpretation('bank-interpretation',`La recarga acumulada pagada a la banca alcanza <b>${fmtCLP(totalBankSurcharge*1e6)}</b>. ${top?`${esc(top.banco)} concentra el mayor monto recomprado del gráfico.`:''} La garantía pública socializó riesgos y costos mientras la obligación permaneció individualizada sobre quienes estudiaron.`)}
function renderMethod(){const q=data.quality.summary;$('quality-score').textContent=`${q.checks_passed} / ${q.checks_total}`;$('updated').textContent=`Datos principales al ${q.as_of}.`;const unique=new Map();data.sources.filter(s=>s.url&&s.http_status>=200&&s.http_status<400).forEach(s=>unique.set(s.url,s));$('source-list').innerHTML=[...unique.values()].map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.institucion)} — ${esc(s.titulo)}</a>`).join('')}
function bind(){$('region-filter').addEventListener('change',renderTerritory);$('metric-filter').addEventListener('change',renderTerritory);$('ies-filter').addEventListener('change',renderInstitutions)}
function $(id){return document.getElementById(id)}function short(s,n){return s&&s.length>n?s.slice(0,n-1)+'…':s}function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
load().catch(e=>{console.error(e);const box=$('error');box.hidden=false;box.textContent='No fue posible cargar los datos. Abre este dashboard desde un servidor web local o público, no directamente como archivo.'});
